apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
      type: frontend
  template:
    metadata:
      name: my-pod
      labels:
        app: my-app
        type: frontend
    spec:
      containers:
      - name: tg-redirect
        image: prajapatdip/tgredirect:c719e2e7b1533ab1fcd31b82f076692c6272cd75
        ports:
        - containerPort: 8081
