apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
      type: frontend
  template:
    metadata:
      name: my-pod
      labels:
        app: my-app
        type: frontend
    spec:
      containers:
      - name: tg-redirect
        image: prajapatdip/tgredirect:6440df646273c53a3d8750a272f176229464e37b
        ports:
        - containerPort: 8081
